### ISSUE TITLE
As a tool user I want to have a clear and simple menu in order to easily find the interface that I'm looking for.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.epaper.webapp#50]
For the ePaper backend we suggest to foresee the following menu:
- [x] Displays:
  - [x] list view noi-techpark/it.bz.opendatahub.epaper.backend#17 ;
  - [x] detail view (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/39):
    - [x] Information (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/40);
    - [x] Content (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/41);
    - [x] Scheduler (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/52);
      - [x] List view;
      - [x] Detail View;
- [ ] Locations (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/43):
  - [x] list view; (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/44)
  - [x] detail view (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/45);
  > Postponed to MVP2
- [x] Template:
  - [x] list view (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/42);
  - [x] detail view (connected issue: https://github.com/noi-techpark/it.bz.opendatahub.epaper.webapp/issues/53);
- Users: (Nice to Have)
  - list view; (Nice to Have)
  - detail view. (Nice to Have)

**Comment by Piiit** [comment]
@sseppi What do you mean with:

```
- Users: (Nice to Have)
  - list view; (Nice to Have)
  - detail view. (Nice to Have)
 ```

These things are managed inside keycloak, do we need them here?
